------Classes------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Classes values('Bismarck','bb','Germany',8,15,42000)
insert into Classes values('Iowa','bb','USA',9,16,46000)
insert into Classes values('Kongo','bc','Japan',8,14,32000)
insert into Classes values('North Carolina','bb','USA',12,16,37000)
insert into Classes values('Renown','bc','Gt.Britain',6,15,32000)
insert into Classes values('Revenge','bb','Gt.Britain',8,15,29000)
insert into Classes values('Tennessee','bb','USA',12,14,32000)
insert into Classes values('Yamato','bb','Japan',9,18,65000)
GO

----Battles------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Battles values('Guadalcanal','19421115')
insert into Battles values('North Atlantic','19410525')
insert into Battles values('North Cape','19431226')
insert into Battles values('Surigao Strait','19441025')
insert into Battles values('#Cuba62a','19621020')
insert into Battles values('#Cuba62b','19621025')
GO

--Ships------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Ships values('California',1921,7)
insert into Ships values('Haruna',1916,3)
insert into Ships values('Hiei',1914,3)
insert into Ships values('Iowa',1943,2)
insert into Ships values('Kirishima',1915,3)
insert into Ships values('Kongo',1913,3)
insert into Ships values('Missouri',1944,2)
insert into Ships values('Musashi',1942,8)
insert into Ships values('New Jersey',1943,2)
insert into Ships values('North Carolina',1941,4)
insert into Ships values('Ramillies',1917,6)
insert into Ships values('Renown',1916,5)
insert into Ships values('Repulse',1916,5)
insert into Ships values('Resolution',1916,5)
insert into Ships values('Revenge',1916,6)
insert into Ships values('Royal Oak',1916,6)
insert into Ships values('Royal Sovereign',1916,6)
insert into Ships values('Tennessee',1920,7)
insert into Ships values('Washington',1941,4)
insert into Ships values('Wisconsin',1944,2)
insert into Ships values('Yamato',1941,8)
insert into Ships values('South Dakota',1941,4)
insert into Ships values('Bismarck',null,null)
insert into Ships values('Duke of York',null,null)
insert into Ships values('Fuso',null,null)
insert into Ships values('Hood',null,null)
insert into Ships values('King George V',null,null)
insert into Ships values('Prince of Wales',null,null)
insert into Ships values('Rodney',null,null)
insert into Ships values('Schamhorst',null,null)
insert into Ships values('South Dakota',null,null)
insert into Ships values('West Virginia',null,null)
insert into Ships values('Yamashiro',null,null)
GO

----Outcomes------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
insert into Outcomes values(23,2,'Sunk')
insert into Outcomes values(1,4,'Ok')
insert into Outcomes values(24,3,'Ok')
insert into Outcomes values(25,4,'Sunk')
insert into Outcomes values(26,2,'Sunk')
insert into Outcomes values(27,2,'Ok')
insert into Outcomes values(5,1,'Sunk')
insert into Outcomes values(28,2,'Damaged')
insert into Outcomes values(29,2,'Ok')
insert into Outcomes values(30,3,'Sunk')
insert into Outcomes values(31,1,'Damaged')
insert into Outcomes values(18,4,'Ok')
insert into Outcomes values(19,1,'Ok')
insert into Outcomes values(32,4,'Ok')
insert into Outcomes values(33,4,'Sunk')
insert into Outcomes values(1,1,'Damaged')
GO